name: The Waters
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29819
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#feefe8'
    - '#565b3b'
    - '#8f9ab8'
    - '#fc0b14'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
